version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: restCRUD

  spring-app:
    restart: always
    image: springappimg
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/restCRUD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysqldb